version: '3'  # Указываем версию Docker Compose.

services:  # Определяем сервисы.

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: 443453  # Пароль root
      MYSQL_DATABASE: fc2   # Имя базы данных
      MYSQL_USER: root           # Имя пользователя
      MYSQL_PASSWORD: 443453      # Пароль пользователя
      MYSQL_COLLATION: latin1_swedish_ci

  web:  # Сервис веб-сервера Apache.
    build: .  # Собираем образ веб-сервера из текущей директории, используя Dockerfile.
    ports:  # Прокидываем порты для доступа к веб-серверу.
      - "8080:80"  # Порт 8080 хоста прокидывается на порт 80 контейнера.
    volumes:  # Определяем примонтированный том для кода веб-приложения.
      - ./html:/var/www/html  # Том для хранения файлов веб-приложения.
    links:  # Создаем связь с сервисом базы данных.
      - db  # Веб-сервер будет в одной сети с контейнером базы данных.

volumes:  # Определяем именованный том для данных базы данных.
  db_data:

